### ISSUE TITLE
Add new functions!

### ISSUE THREAD

**Issue by animetrom** [3dproger/AxelChat#280]
Firstly congratulations on the wonderful project!
I would like to ask you to also add DLive, please.
Youtube and Kick could have a login option too, if possible.

**Comment by 3dproger** [comment]
Hello! Thank you very much for your rating!
Support for the DLive is planned. Perhaps it will be in a soon update

The implementation of logging into YouTube is still problematic due to the not entirely suitable YouTube API for this. Perhaps something will change in the future

The implementation of login to Kik is also in question, since they still do not have an open API

**Comment by animetrom** [comment]
Thanks!

**Comment by 3dproger** [comment]
Hello! The new version now has compatibility with DLive

**Comment by animetrom** [comment]
Thanks man!!!
Compatibility on Nimo.tv please!

**Comment by 3dproger** [comment]
Okay, I think I can close this issue. And for Nimo.tv I have already created a issue: https://github.com/3dproger/AxelChat/issues/248
